from setuptools import setup, find_packages

setup(
    name='logNow',
    version='0.2.2',    
    description='logNow" is a Python package created to simplify logging for developers working on Python applications. The package provides a simple logging function that allows developers to output log messages to a file with timestamps, instead of using the standard "print" statement.',
    url='https://github.com/NapoII/logNow',
    author='Napo_II',
    author_email='Napo_the_II@protonmail.com',
    license='MIT License',
    packages=find_packages(),
    install_requires= [],

    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Science/Research',
        'Intended Audience :: Developers',
        'Intended Audience :: Information Technology',
        'Intended Audience :: Manufacturing',
        'Intended Audience :: Other Audience',
        'Intended Audience :: System Administrators',
        
        'License :: OSI Approved :: MIT License',  
        'Operating System :: POSIX :: Linux',        
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Topic :: Documentation',
        'Topic :: Printing',
        'Topic :: Scientific/Engineering',
        'Topic :: Software Development',
        'Topic :: Software Development :: Build Tools',
        'Topic :: Software Development :: Debuggers',
        'Topic :: Software Development :: Localization',
        'Topic :: Software Development :: Testing',
        'Topic :: System',
        'Topic :: System :: Console Fonts',
        'Topic :: System :: Logging',
        'Topic :: System :: Operating System',
        'Topic :: Utilities',
        ],)